### ISSUE TITLE
Add option to allow duplicate files

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/archivebot#1]
Right now, duplicate files will be ignored.
The duplication is detected whether there already is a file with this name in the target directory.
There should be an option to disable this feature and place the new file besides any old files

Duplicate files from the same chat will still be ignored.

**Comment by drusc0** [comment]
Hi @Nukesor,

I am just starting to contribute to open source. Do you mind if I give you a hand? Thanks! any other hints you might give me to lead me in the right direction I would appreciate it :).

**Comment by Nukesor** [comment]
Hi @drusc0 :)

Thanks for offering your help! Sadly I already implemented this feature, since I noticed that this might require some refactoring and since I need this feature as a prerequisite for the next feature which I'm already working on. ...
I already wanted to remove the `good first issue` Label, but you were just too fast :D 
But thanks anyway for offering help ;)

**Comment by drusc0** [comment]
ok thanks @Nukesor ! let me know if there is anything else I can help with to start getting familiar with the code base.
