### ISSUE TITLE
Execution error?

### ISSUE THREAD

**Issue by LoJbaDelRoito** [Nukesor/archivebot#11]
Hi, 
It's me again.

I found an error; 
`/archivebot/sentry.py",` line 16, in __init__
    if config.SENTRY_TOKEN is not None:
AttributeError: 'Config' object has no attribute `'SENTRY_TOKEN'`
This happens because in config.py, it's called SENTRY_KEY...

Now the big question...
After i execute the command 
`poetry run `./main.py``

Bash is working, but without writing anything.
So I try /start on telegram. (and other command)
I can see the creation of the folder on my pc, and the generation of the .session, .db file; 
but I don't get any response from the bot itself. 

The only command I get answered is /scan_chat. (bot:Starting full chat scan.)
At the same time a traceback appears in the bash.

https://pastebin.com/rcjMUnag

Probably there are two different problem.

Thanks to the availability.

**Comment by Nukesor** [comment]
The SENTRY_KEY is supposed to be left in your config.py, but set to None.
It should work, if you add it again.

I'm planning to add proper configuration files for all my bots soon. This should prevent such bugs.

**Comment by Nukesor** [comment]
Configuration files have been added. Please update the project and start and follow the instructions.
I'm closing this ticket for now :)
