### ISSUE TITLE
Errorno 13

### ISSUE THREAD

**Issue by dedsec85** [Nukesor/archivebot#13]
Hello 
when i try to run initdb.py by command poetry run ./initdb.py i get the following error:
PermissionError: [Errno 13] Permission denied
what should i do?

**Comment by dedsec85** [comment]
i changed the folder and cloned files directly from git hub to my server and it fixed the problem however i get this error now 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from archivebot.archivebot import main
  File "/home/pi/archivebot/archivebot/archivebot.py", line 41, in <module>
    os.mkdir(config['download']['/download'])
KeyError: '/download'
which means i should change target_dir in archivebot.py 
however i have no clue how i can change it could you help me with this please?

**Comment by Nukesor** [comment]
Sorry for the late answer. 

Well, the original error came (probably) from missing write permissions in the current folder.

The second error is kind of weird. The crashing line doesn't exist in the code. (The `/download` part)
Where did you get the code from? Did you do a fresh clone from master?
