### ISSUE TITLE
retry failed/cancelled download

### ISSUE THREAD

**Issue by adocampo** [Nukesor/archivebot#14]
Hi there!

I'm using this awesome bot to in conjunction with [medusa](https://github.com/pymedusa/medusa) to save and then rename and place the file into the correct path.

Sometimes, but, medusa moves the file when it didn't complete to download, so I need to re-download it again, and it seems it cannot be downloaded more than once. I have tried to `/allow_duplicates` and `/clear_history` but it seems it does nothing. (in fact, the only two commands with any output are `/start@username` and `/stop@username` commands.

Am I doing something wrong?

**Comment by Nukesor** [comment]
Did you do `/allow_duplicates@username true`?
Try `/info@username` to see the current settings for a chat

**Comment by adocampo** [comment]
I didn't do (I miss the @username part on the commands) but I did just now. Still seems to not to download already downloaded files.
```
Current settings:

Name: 19338....
Active: True
Accepted Media: document
Verbose: True
Allow duplicates: True
Sort files by User: True
```

**Comment by Nukesor** [comment]
Allow duplicates is basically a flag, which enable downloading of files that have the same download.
If you want to download files that actually failed to download, you need to start a `/scan_chat`
This will go through the whole chat history and download files (if they haven't been downloaded yet)

**Comment by adocampo** [comment]
I have this on my history chat
![imagen](https://user-images.githubusercontent.com/2266612/69144634-fdbecc00-0acb-11ea-97be-74f5761700ff.png)
But it doesn't donwload anything
![imagen](https://user-images.githubusercontent.com/2266612/69144402-8852fb80-0acb-11ea-9c9b-5e15718bebe6.png)

I'm on my own chat (Saved Messages), can be this perhaps? (I don't know if/how I can download to a bot). I cannot see either a verbosed ouput nor in the chat neither in the command line output

**Comment by Nukesor** [comment]
That's because this is probably a photo.
As you can see, your accepted media is set to `documents`, which only includes file uploads.
Type `/accept@user document photo`

It's obvious, that some things in the current documentation are unclear. It would be awesome, if you could adjust the documentation text, remove any uncertainties and create a PR :)

**Comment by Nukesor** [comment]
Verbose:
This is from the docs:
/verbose ['true', 'false'] The bot will complain if there are duplicate files or uncompressed images are sent, whilst not being accepted.

**Comment by Nukesor** [comment]
Just tested the verbose output. Seems to be silently ignored.
Feel free to debug and create a PR :) Shouldn't be too hard, the code base is pretty straight forward.

**Comment by adocampo** [comment]
> That's because this is probably a photo.
> As you can see, your accepted media is set to `documents`, which only includes file uploads.
> Type `/accept@user document photo`
> 
> It's obvious, that some things in the current documentation are unclear. It would be awesome, if you could adjust the documentation text, remove any uncertainties and create a PR :)

Still doesn't work, and as verbose tells nothing, it's quite hard to know what's happening.
I can PR the changes to de documentation to be a bit more clear, and perhaps after the tests, if I can create a systemd unit file to autostart the bot on boot.

> Just tested the verbose output. Seems to be silently ignored.
> Feel free to debug and create a PR :) Shouldn't be too hard, the code base is pretty straight forward.

I can't take a look, yet I do not know anything about telegram bots, to see at least why verbose isn't working.

**Comment by Nukesor** [comment]
A few lines in the documention would be very much appreciated, though ;)

**Comment by adocampo** [comment]
The `/clear_history@username` did the trick.
I'm gonna PR some suggestions to the README, so command won't be ambiguous.

**Comment by Nukesor** [comment]
Nice. Thanks a lot! :+1:
