### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by vinuelz** [Nukesor/archivebot#16]
Im getting the following error when trying to install and later trying to run the bot:

poetry run ./main.py

[FileNotFoundError]  
[Errno 2] No such file or directory: './main.py': './main.py'

It works if i do **poetry run python ./main.py** but i do not get any output and the bot does not answer either.

How can i fix this? Is there some sort of verbose output?

Thanks for your awesome work!

**Comment by Nukesor** [comment]
No ouptut is normal. There shouldn't be any output as long as there are no exceptions.

Check whether the bot is working normally by issueing commands

**Comment by Nukesor** [comment]
I'm not sure, why poetry doesn't support the normal `run ./main.py` any longer, but somehow it doesn't work anymore.
Docs are updated.

**Comment by vinuelz** [comment]
Maybe im doing something wrong (never ran an userbot before).

i tried everything i could imagine, where exactly should i issue the commands?

**Comment by Nukesor** [comment]
In group chats the bot expects a command in combination with its username. (In userbot mode that's your own username) E.g. /start@some_bot_name or /start@Nukesor
