### ISSUE TITLE
use userbot command

### ISSUE THREAD

**Issue by mhsharifi96** [Nukesor/archivebot#17]
hello
I completed installation and got App api_id and App api_hash in my.telegram, and program run successfully(without any error) but I have one  question:
In userbot mod :
how can I use commands in "userbot"?
for example in doc explain it : 
```In group chats the bot expects a command in combination with its username. (In userbot mode that's your own username) E.g. /start@some_bot_name or /start@Nukesor```
what's the mean and  how can i use  command ? 

tnx

**Comment by Nukesor** [comment]
well. Just type `/start@your_user_name` in any chat.
Naturally, you need a telegram user handle for this to work (`@name`)
