### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ManuXD32** [Nukesor/archivebot#25]
I have tried to deploy de bot several times but It just doesn't work, the "just run" command just shows that poetry is running python main.py run and that's pretty much It, no errors in screen and the bot just doesn't answer to anything. 
Has anyone else had this problem?

**Comment by Nukesor** [comment]
Nope. Not sure what your problem is tbh.

Not getting any log output doesn't help either.

**Comment by ManuXD32** [comment]
Okay, thank you anyway!!
