### ISSUE TITLE
installation errors 

### ISSUE THREAD

**Issue by arvs47** [Nukesor/archivebot#5]
% make
% ./venv/bin/activate
% ./initdb.py
% ./main.py
installed make 

/venv/bin/activate
usr@instance-4:~/archivebot$ ./initdb.py
-bash: ./initdb.py: /bin/env: bad interpreter: No such file or directory
usr@instance-4:~/archivebot$ ./main.py
-bash: ./main.py: /bin/env: bad interpreter: No such file or directory
usr@instance-4:~/archivebot$ 

should i move them to the bin venv folder or 
 
 ,ubuntu os google cloud vps installed with ubuntu , 

if any other software needed please mention them

**Comment by Nukesor** [comment]
I'm not quite sure what your exact problem is.
Everything should work fine. It looks like you don't have any python version installed?
You obviously need a python3 version (everything above 3.5)
